### ISSUE TITLE
build: global vs project arguments

### ISSUE THREAD

**Issue by ignatenkobrain** [jdieter/zchunk#1]
https://github.com/jdieter/zchunk/blob/bb74abe0dfe589643c25c0617ad2de8863e32e06/meson.build#L16

Please use `add_project_arguments()`

**Comment by jdieter** [comment]
Done in https://github.com/jdieter/zchunk/commit/c47b64b31ca4f53b741b98ff0620738c9fa8ca6f

**Comment by jdieter** [comment]
Thanks for the pointer
